# taken from https://github.com/cristianadam/HelloWorld

name: Test Github actions for a C++ project with a CMake/Ninja build

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  NINJA_VERSION: 1.9.0
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "macOS-latest clang",
#            artifact: "macOS-clang.tar.xz",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }
          - {
            name: "macOS-latest gcc9",
#            artifact: "macOS-gcc.tar.xz",   # what's that really used for - the build
            os: macos-latest,               # where is this specified
            cc: "gcc-9", cxx: "g++-9"       # how do I install that
                                            # check how these are exported within the session
          }

    steps:
      - uses: actions/checkout@v1           # what's that

      - name: Download and install homebrew
        id: step_homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

      - name: Install gcc, cmake, ninja  # install gcc conditionally
        id: get_dev_tools
        run: brew install gcc cmake ninja

      - name: Install gtest from source
        id: step_gtest
        run: |
          git clone https://github.com/google/googletest.git
          mkdir googletest/build && cd googletest/build
          CXX=${{matrix.config.cxx}} CX=${{matrix.config.cc}} cmake .. -DBUILD_SHARED_LIBS=ON
          make
          make install

      - name: Build project
        id: step_build_project
        run: |
          mkdir test_build
          cd test_build
          CXX=${{matrix.config.cxx}} CX=${{matrix.config.cc}} cmake -S.. -B. -G"Ninja"
          ninja gmp_test

      - name: Run tests  # fail is the return is nonzero
        id: step_run_project_tests
        run: |
          ./test_build/examples/gmp_test