# taken from https://github.com/cristianadam/HelloWorld

name: Testing Github actions

on:
  push
  pull_request

env:
  CMAKE_VERSION: 3.16.2
  NINJA_VERSION: 1.9.0
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
#          - {
#            name: "macOS-latest clang",
#            artifact: "macOS-clang.tar.xz",
#            os: macos-latest,
#            cc: "clang", cxx: "clang++"
#          }
          - {
            name: "macOS-latest gcc9",
            artifact: "macOS-gcc.tar.xz",
            os: macos-latest,
            cc: "gcc-9", cxx: "g++-9"
          }
          - {
            name: "Ubuntu-latest gcc",
            artifact: "Ubuntu.tar.xz",
            os: ubuntu-latest,
            cc: "gcc-9", cxx: "g++-9"
          }

    steps:
      - uses: actions/checkout@v1  # this set up the virtual environment, which has a whole lot
                                   # as of this writing: gcc9, clang10, cmake3.17, homebrew...

      - name: Download and install homebrew
        id: step_homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

      - name: Install missing dev tools
        id: get_dev_tools
        run: brew install ninja
        # echo "::set-output name=ebasi::OK TEST THIS"

      - name: Install gtest from source
        id: step_gtest
        run: |
          git clone https://github.com/google/googletest.git
          mkdir googletest/build && cd googletest/build
          CXX=${{matrix.config.cxx}} CC=${{matrix.config.cc}} cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=ON
          ninja
          sudo ninja install

      - name: Build project
        id: step_build_project
        run: |
          mkdir test_build
          cd test_build
          CXX=${{matrix.config.cxx}} CC=${{matrix.config.cc}} cmake -S.. -B. -G"Ninja"
          ninja gmp_test

      - name: Run tests
        id: step_run_project_tests
        run: ./test_build/examples/gmp_test
        # echo "${{steps.get_dev_tools.outputs.ebasi}}"